DEFINE_LEVEL("Level Template", Level_Template, Mars, 4, 0)
DEFINE_LEVEL("Boot Camp", Boot_Camp, Mars, 2, 0 | LevelMetadataFlagsCampaign | LevelMetadataFlagsMultiplayer)
DEFINE_LEVEL("Sojourner", Sojourner, Mars, 4, 0 | LevelMetadataFlagsCampaign)
DEFINE_LEVEL("The Octogon", The_Octogon, Mars, 4, 0 | LevelMetadataFlagsMultiplayer)
DEFINE_LEVEL("Course 01", Course_01, Mars, 4, 0 | LevelMetadataFlagsMultiplayer)
DEFINE_LEVEL("Sojourner 2", Sojourner_2, Mars, 4, 0 | LevelMetadataFlagsCampaign | LevelMetadataFlagsMultiplayer)
