#ifndef SRC_AUDIO_CLIPS_H
#define SRC_AUDIO_CLIPS_H

#define SOUNDS_DEATHSFX 0
#define SOUNDS_DOG_PANT_IDLE_2 1
#define SOUNDS_DOG_WALKING_LOOP_2 2
#define SOUNDS_DOG_JUMP_GRUNT_5 3
#define SOUNDS_PUNCH 4
#define SOUNDS_PUNCHIMPACT 5
#define SOUNDS_DOG_INJURED_GRUNT_2 6
#define SOUNDS_DOG_ATTACK2 7
#define SOUNDS_DOG_JUMP_GRUNT_6 8
#define SOUNDS_DOG_JUMP_GRUNT_2 9
#define SOUNDS_DOG_BARK_3 10
#define SOUNDS_DOG_BARK_7 11
#define SOUNDS_DOG_INJURED_GRUNT_1 12
#define SOUNDS_DOG_BARK_5 13
#define SOUNDS_DOG_WALKING_LOOP_1 14
#define SOUNDS_DOG_JUMP_GRUNT_1 15
#define SOUNDS_DOG_JUMP_GRUNT_7 16
#define SOUNDS_DOG_JUMP_GRUNT_4 17
#define SOUNDS_POWERUP_PICKUP 18
#define SOUNDS_DOG_ATTACK1 19
#define SOUNDS_DOG_BARK_6 20
#define SOUNDS_DOG_BARK_2 21
#define SOUNDS_DOG_JUMP_GRUNT_3 22
#define SOUNDS_DOG_ATTACK3 23
#define SOUNDS_UI_SELECT3 24
#define SOUNDS_DOG_BARK_1 25
#define SOUNDS_LOGOLAUGHING 26
#define SOUNDS_DOG_PANT_IDLE_1 27
#define SOUNDS_UI_SELECT2 28
#define SOUNDS_DOG_BARK_4 29
#define SOUNDS_VICTORYMUSIC 30
#define SOUNDS_CONTROLSCRAMBLE 31
#define SOUNDS_ITEMSPAWN 32
#define SOUNDS_SPAWN 33
#define SOUNDS_UI_SELECT 34
#define SOUNDS_FLAGCAP 35
#define SOUNDS_CATMEOW1 36
#define SOUNDS_LEVELMUSIC_COLDORBITFASTER 37
#define SOUNDS_LEVELMUSIC_DANAIDES 38
#define SOUNDS_FOOTSTEP0 39
#define SOUNDS_MAP_CHARACTER_SELECT_OR_VICTORY_MUSIC 40
#define SOUNDS_LEVELMUSIC_HUNTERSEEKER_MASTERED 41
#define SOUNDS_LEVELMUSIC_COLDORBIT 42
#define SOUNDS_FOOTSTEP2 43
#define SOUNDS_LEVELMUSIC_FERMIPARADOX_MASTERED 44
#define SOUNDS_LEVELMUSIC_PLANUM_BOREUM_XMAS 45
#define SOUNDS_LEVEL_MUSICTANGERINEVAMP 46
#define SOUNDS_FOOTSTEP1 47
#define SOUNDS_FOOTSTEP3 48
#define SOUNDS_FOOTSTEP4 49
#define SOUNDS_LEVELMUSIC_DNB_NO2 50
#define SOUNDS_ITEMWAIT 51
#define SOUNDS_FOOTSTEPSWALKCYCLE 52

#endif