#ifndef SRC_AUDIO_CLIPS_H
#define SRC_AUDIO_CLIPS_H

#define SOUNDS_DEATHSFX 0
#define SOUNDS_DOG_PANT_IDLE_2 1
#define SOUNDS_DOG_WALKING_LOOP_2 2
#define SOUNDS_DOG_JUMP_GRUNT_5 3
#define SOUNDS_PUNCHIMPACT 4
#define SOUNDS_DOG_INJURED_GRUNT_2 5
#define SOUNDS_DOG_ATTACK2 6
#define SOUNDS_FOOTSTEP2 7
#define SOUNDS_DOG_JUMP_GRUNT_6 8
#define SOUNDS_DOG_JUMP_GRUNT_2 9
#define SOUNDS_DOG_BARK_3 10
#define SOUNDS_FOOTSTEP0 11
#define SOUNDS_DOG_BARK_7 12
#define SOUNDS_DOG_INJURED_GRUNT_1 13
#define SOUNDS_DOG_BARK_5 14
#define SOUNDS_DOG_WALKING_LOOP_1 15
#define SOUNDS_FOOTSTEP3 16
#define SOUNDS_DOG_JUMP_GRUNT_1 17
#define SOUNDS_DOG_JUMP_GRUNT_7 18
#define SOUNDS_DOG_JUMP_GRUNT_4 19
#define SOUNDS_DOG_ATTACK1 20
#define SOUNDS_DOG_BARK_6 21
#define SOUNDS_DOG_BARK_2 22
#define SOUNDS_FOOTSTEP4 23
#define SOUNDS_DOG_JUMP_GRUNT_3 24
#define SOUNDS_FOOTSTEP1 25
#define SOUNDS_DOG_ATTACK3 26
#define SOUNDS_UI_SELECT3 27
#define SOUNDS_DOG_BARK_1 28
#define SOUNDS_DOG_PANT_IDLE_1 29
#define SOUNDS_UI_SELECT2 30
#define SOUNDS_DOG_BARK_4 31
#define SOUNDS_UI_SELECT 32
#define SOUNDS_FLAGCAP 33
#define SOUNDS_CATMEOW1 34
#define SOUNDS_LEVELMUSIC_EDGARISGOAT 35
#define SOUNDS_LEVELMUSIC_FERMIPARADOX 36

#endif