#ifndef SRC_AUDIO_CLIPS_H
#define SRC_AUDIO_CLIPS_H

#define SOUNDS_DOG_PANT_IDLE_2 0
#define SOUNDS_DOG_WALKING_LOOP_2 1
#define SOUNDS_DOG_JUMP_GRUNT_5 2
#define SOUNDS_DOG_INJURED_GRUNT_2 3
#define SOUNDS_DOG_ATTACK2 4
#define SOUNDS_DOG_JUMP_GRUNT_6 5
#define SOUNDS_DOG_JUMP_GRUNT_2 6
#define SOUNDS_DOG_BARK_3 7
#define SOUNDS_DOG_BARK_7 8
#define SOUNDS_DOG_INJURED_GRUNT_1 9
#define SOUNDS_DOG_BARK_5 10
#define SOUNDS_DOG_WALKING_LOOP_1 11
#define SOUNDS_DOG_JUMP_GRUNT_1 12
#define SOUNDS_DOG_JUMP_GRUNT_7 13
#define SOUNDS_DOG_JUMP_GRUNT_4 14
#define SOUNDS_DOG_ATTACK1 15
#define SOUNDS_DOG_BARK_6 16
#define SOUNDS_DOG_BARK_2 17
#define SOUNDS_DOG_JUMP_GRUNT_3 18
#define SOUNDS_DOG_ATTACK3 19
#define SOUNDS_DOG_BARK_1 20
#define SOUNDS_DOG_PANT_IDLE_1 21
#define SOUNDS_DOG_BARK_4 22
#define SOUNDS_UI_SELECT 23
#define SOUNDS_FLAGCAP 24
#define SOUNDS_CATMEOW1 25
#define SOUNDS_LEVELMUSIC_EDGARISGOAT 26
#define SOUNDS_LEVELMUSIC_FERMIPARADOX 27

#endif